---
language: node_js
node_js:
- 6
- 8
sudo: false
cache:
  directories:
  - node_modules
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
before_script:
    - yarn install
